name: CMake

on: push

env:
  BUILD_TYPE: Release
  CXX_STANDARD: 17

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        shared:
          - True
          - False

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies - macOS
        run: brew install libomp
        if: matrix.os == 'macos-latest'

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_CXX_STANDARD=$CXX_STANDARD -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=${{matrix.shared}}

      - name: Build
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: ctest -C $BUILD_TYPE
